### ISSUE TITLE
Missing cpu_temperature sensor

### ISSUE THREAD

**Issue by shmick** [ollo69/ha_asuswrt_custom#2]
Testing out the integration.
Router = RT-AC68U running Merlin 386.7

The integration shows these sensors from the router:
- devices_connected
- download
- download_speed
- upload
- upload_speed

The official asuswrt also provides the `cpu_temperature` sensor, but it's not being reported with `ha_asuswrt_custom`

**Comment by ollo69** [comment]
I will add additional sensors in future release. For now I concentrate on device tracker reliability.

**Comment by shmick** [comment]
Sounds good. So far device tracker is working fine.

**Comment by shmick** [comment]
@ollo69 this integration has been working well since installing it. Device tracking works well and no noticeable increase in memory pressure on my AC68U router. Hopefully this can make its way into HA Core sooner than later.

**Comment by ollo69** [comment]
CPU temperature now is available. I close this.
