### ISSUE TITLE
Detecting Home

### ISSUE THREAD

**Issue by JorgeMaTeixeira** [ollo69/ha_asuswrt_custom#24]
I found today that since latest update this integration is marking me and my wife at home when for sure we are not home.. I have reloaded the integration and I will keep an eye on the situation.

**Comment by ollo69** [comment]
Be sure that integration is configured with http protocol. You can check from diagnostics or you can just reconfigure enabling advanced option so that you have the option to choose the communication protocol.
Wrong home detection is a typical issue related to old ssh library.

**Comment by JorgeMaTeixeira** [comment]
I have reconfigured to unsure I'm using https, but it's the same..
I have downgraded the integration version to test..

**Comment by JorgeMaTeixeira** [comment]
Problem still present even with old version..
Maybe related with latest asus firmware?

**Comment by JorgeMaTeixeira** [comment]
I'm testing another asus integration and the problem is present.. For sure is a router firmware problem..

**Comment by JorgeMaTeixeira** [comment]
I trying to understand this problem, but don't have knowledge to do this myself :p
what i can share is, for some reason me and my wife sometimes are been marked as being home, and our devices are not connected to the network, i checked in those momments our devices are not visible in the asus firmware config page.

**Comment by ollo69** [comment]
For starting attach integration diagnostics.

**Comment by JorgeMaTeixeira** [comment]
[config_entry-asuswrt_custom-98bb00b0d9b4a10f7a48a67c90ddb5fb.json.txt](https://github.com/ollo69/ha_asuswrt_custom/files/11546173/config_entry-asuswrt_custom-98bb00b0d9b4a10f7a48a67c90ddb5fb.json.txt)

**Comment by JorgeMaTeixeira** [comment]
After a lot of fight with my asus devices I think the problem is solved.. Made some reboots and resets..
