### ISSUE TITLE
Device Tracker Entities are disabled

### ISSUE THREAD

**Issue by auanasgheps** [ollo69/ha_asuswrt_custom#25]
Hi,
I just installed this integration by uninstalling the official one. I'm having issues with Device Tracker entities.

- RT-AC86U
- Merlin 3.0.0.4.386.11_0 
- HTTP method
- Latest HA and integration

The integration is working fine for router info.
The device tracker is working fine for devices that already have an integration in HA that uses their IP address, like Shelly, Broadlink etc (they're seen as a "Device" in Asus integration too). But for devices that do not have such integration such as my laptop or my phone, the entity exists but shows as disabled.

Can you help?
![image](https://github.com/ollo69/ha_asuswrt_custom/assets/20586878/3135d32c-414f-4855-9e58-63c2d43d3050)

**Comment by auanasgheps** [comment]
Allright, I enabled it and seems that status is reported as expected. Don't know why, that's weird.

**Comment by auanasgheps** [comment]
Update: devices are all detected as "home" but they're not.

**Comment by auanasgheps** [comment]
Update2: the disconnected devices are now reported as away. Not sure if it's the integration or the router...

**Comment by ollo69** [comment]
Entity related to tracked devices that do not provide additional HA features ( as switch, light and so on) are always created in disabled status and without an associated device, this is as HA works. You must manually enable the entities that you want to track. All tracked entities when disconnected from router remain in status home for a specific period. You can change this period in integration config option (I think that default is 5 minutes, but I'm not sure)

**Comment by auanasgheps** [comment]
Thank you!
