### ISSUE TITLE
Feat: WAN Status Sensors

### ISSUE THREAD

**Issue by PeteRager** [ollo69/ha_asuswrt_custom#8]
Add sensors to track WAN status via async_get_wan_info

While all the info could be good to have

        Format: {"status": "1", "statusstr": "'Connected'", "type": "'dhcp'", "ipaddr": "'192.168.1.2'",
                 "netmask": "'255.255.255.0'", "gateway": "'192.168.1.1'", "dns": "1.1.1.1'",
                 "lease": "86400", "expires": "81967", "xtype": "''", "xipaddr": "'0.0.0.0'",
                 "xnetmask": "'0.0.0.0'", "xgateway": "'0.0.0.0'", "xdns": "''", "xlease": "0",
                 "xexpires": "0"}

The main ones needed are:
- status
- Ipaddr
- gateway
- dns

use case, assessing health of wan connection when internet ping sensors go down, to determine if cable modem or router may need to be restarted.

**Comment by ollo69** [comment]
Good idea, I will add to next release.

**Comment by ollo69** [comment]
This sensors are now available in new release.

**Comment by PeteRager** [comment]
That was fast!! I’ll load it up tomorrow.

**Comment by PeteRager** [comment]
Installed it today.  Setup worked and I was able to enable those WAN entities and get data.  

When I disconnect the coax from the modem, then sensors still reported as connected.  I then ran home_assistant.update_entity on the connected status and that did not change it.  I logged into the router and it showed its state as disconnected.  I then restarted home assistant and the WAN entities did not change.  They all showed the data from when it was last connected.  So it kind of seem like we are getting the old data from the router.

Is there some debugging or data I should try to grab from the Asus, so we can see what is going on?

**Comment by PeteRager** [comment]
I ran a different test.  In this test I pulled the power from the modem.  Once I did this on the next scan cycle the integration reported ip as 0.0.0.0, gw as 0.0.0.0 and connected as connected.  

- 
![8A493EB4-2A46-4CA4-9026-5C8446D06A6B](https://user-images.githubusercontent.com/76050312/210416580-98d7071e-7efd-4c33-8567-2d86e01c653a.jpeg)

It looks like as long as the media isn’t disconnected and it’s DNS lease is still valid it holds onto those values.  Which I suppose is reasonable behavior.   So it seems like the issue is the connected state not working in either scenario.

**Comment by ollo69** [comment]
I think this is my fault. I released this version without really testing value returned by the router when disconnected. Just because I would leave test to you😁. I will check this better and will return with a new version.

**Comment by PeteRager** [comment]
Sounds good, I think this line is a bit optimistic 

https://github.com/ollo69/ha_asuswrt_custom/blob/f92ab7f85c74a7e615bb70148e1bc6b0c068f48a/custom_components/asuswrt_custom/binary_sensor.py#L82

**Comment by ollo69** [comment]
Released new version (and tested), now WAN sensor should work properly. Please give me your feedback.

**Comment by PeteRager** [comment]
Thanks.  Will try tomorrow AM

**Comment by PeteRager** [comment]
Ran though the tests and it work.  Thank you for the fast turn-around.
